# Pune Property Price Analysis🏠🏘️

## 01. Cleaning the Dataset

## Business Understanding
***Problem*** ***Statement***

The real estate market in Pune exhibits significant variation in property prices based on factors such as location, total area, configuration, amenities, and furnishing status. However, property data available across platforms is often inconsistent, incomplete, and unstructured, making it difficult for buyers to accurately estimate fair property prices or compare available options efficiently.

As a result, there is a need for a data-driven system that can clean, structure, and analyze property data to:

* Predict property prices accurately

* Provide intelligent recommendations based on user preferences

* Offer interactive insights into market trends

***Objective of Notebook***

To analyze and prepare a raw Pune property dataset for machine learning by:


*   Understanding the structure and quality of the data.
*   Identifying inconsistencies, missing values and non atomic features.
*  cleaning and Preparing the dataset for further analysis and modeling.

## Data Understanding

***Data Descripition***

The dataset Pune_property_data.csv contains 37,500+ property listings. Each row represents a single property listing, and each column describes a specific attribute related to property.

***Key Attributes Observed***
Some important columns include:



- bhk – Number of bedrooms

- bathroom – Number of bathrooms

- area / carpetarea – Property size information

- price / pricepersquare – Pricing details

- locality – Area within Pune

- projectname – Name of the residential project

- status – Ready to move / Under construction

- amenitiesavailable / amenitiesnot – Amenities information

In [137]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [138]:
data = pd.read_csv("/content/Pune_property_data.csv")
data.head()

,Unnamed: 0,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,...,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
0,0,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","24 X 7 Security,Children's play area,Club Hous...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,...,2,Road View,Co-Operative Society,NaN,27000000,"₹ 16,759/ sq ft",Bhansali Prive Rio,40 feet,Ready to move,6
1,1,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Sports Facility,Landscape...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,...,NaN,NaN,Freehold,NaN,7610050,"₹ 5,950/ sq ft",Goel Ganga Platino,NaN,Ready to move,NaN
2,2,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",Sports Facility,670 sq ft,NaN,1,1 BHK Apartment,NaN,...,NaN,NaN,Freehold,NaN,4100000,"₹ 6,119/ sq ft",Vilas Javdekar Yashwin,NaN,Ready to move,NaN
3,3,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,24 X 7...","Sports Facility,Landscaped Gardens",956 sq ft,NaN,2,2 BHK Apartment,615 sq ft,...,NaN,NaN,Freehold,NaN,5736000,"₹ 6,000/ sq ft",Rohan Ishan,NaN,Ready to move,NaN
4,4,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","Club House,Swimming Pool,Sports Facility,Joggi...","1,706 sq ft",1,3,3 BHK Apartment,1195 sq ft,...,2,Road View,Freehold,NaN,29002000,"₹ 17,000/ sq ft",Swojas Aavishkar,60 feet,Ready to move,9

In [139]:
# Total rows and cols
print("Total Rows and Columns are: ", data.shape)

Total Rows and Columns are:  (37539, 24)

In [140]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37539 entries, 0 to 37538
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          37539 non-null  int64
 1   additionalrooms     9321 non-null   object
 2   age                 27637 non-null  object
 3   amenitiesavailable  34445 non-null  object
 4   amenitiesnot        34286 non-null  object
 5   area                37518 non-null  object
 6   balconies           21911 non-null  object
 7   bathroom            34667 non-null  object
 8   bhk                 37538 non-null  object
 9   carpetarea          8622 non-null   object
 10  facing              30919 non-null  object
 11  floor               31919 non-null  object
 12  locality            37538 non-null  object
 13  neworold            37538 non-null  object
 14  opensides           11605 non-null  object
 15  overlooking         17140 non-null  object
 16  ownership           28156 non-null  object
 17  possesiondate       4736 non-null   object
 18  price               37538 non-null  object
 19  pricepersquare      37538 non-null  object
 20  projectname         24129 non-null  object
 21  roadfaceing         6875 non-null   object
 22  status              36078 non-null  object
 23  totalfloor          24114 non-null  object
dtypes: int64(1), object(23)
memory usage: 6.9+ MB

In [141]:
# Total Null values per columns
print("Total Null values per columns: ")
data.isnull().sum().sort_values()

Total Null values per columns:

Unnamed: 0                0
neworold                  1
locality                  1
bhk                       1
price                     1
pricepersquare            1
area                     21
status                 1461
bathroom               2872
amenitiesavailable     3094
amenitiesnot           3253
floor                  5620
facing                 6620
ownership              9383
age                    9902
projectname           13410
totalfloor            13425
balconies             15628
overlooking           20399
opensides             25934
additionalrooms       28218
carpetarea            28917
roadfaceing           30664
possesiondate         32803
dtype: int64

In [142]:
# Total columns Names
print("Coluns Are: ")
data.columns

Coluns Are:

Index(['Unnamed: 0', 'additionalrooms', 'age', 'amenitiesavailable',
       'amenitiesnot', 'area', 'balconies', 'bathroom', 'bhk', 'carpetarea',
       'facing', 'floor', 'locality', 'neworold', 'opensides', 'overlooking',
       'ownership', 'possesiondate', 'price', 'pricepersquare', 'projectname',
       'roadfaceing', 'status', 'totalfloor'],
      dtype='object')

In [143]:
# Duplicate Rows
data.duplicated().sum()

np.int64(0)

## Data Preparation

***Cleaning the Data set***

In [144]:
# dropping the Unwanted Columns
data.drop(["Unnamed: 0", "amenitiesnot", "projectname"], axis=1, inplace = True)

In [145]:
data

,additionalrooms,age,amenitiesavailable,area,balconies,bathroom,bhk,carpetarea,facing,floor,...,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,roadfaceing,status,totalfloor
0,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,West,"3,",...,New,2,Road View,Co-Operative Society,NaN,27000000,"₹ 16,759/ sq ft",40 feet,Ready to move,6
1,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,7610050,"₹ 5,950/ sq ft",NaN,Ready to move,NaN
2,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",670 sq ft,NaN,1,1 BHK Apartment,NaN,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,4100000,"₹ 6,119/ sq ft",NaN,Ready to move,NaN
3,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,24 X 7...",956 sq ft,NaN,2,2 BHK Apartment,615 sq ft,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,5736000,"₹ 6,000/ sq ft",NaN,Ready to move,NaN
4,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,706 sq ft",1,3,3 BHK Apartment,1195 sq ft,West,"6,",...,New,2,Road View,Freehold,NaN,29002000,"₹ 17,000/ sq ft",60 feet,Ready to move,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37534,1 rooms( pooja room ),0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,084 sq ft",1,2,2 BHK Apartment,814 sq ft,East,"6,",...,New,4,Garden View,Freehold,NaN,8363000,"₹ 7,714/ sq ft",NaN,Ready to move,12
37535,1 rooms( pooja room ),NaN,"Lift Available,Car Parking,Power Backup,24 X 7...",953 sq ft,1,2,2 BHK Apartment,706 sq ft,East,"7,",...,New,4,Garden View,Freehold,01-12-2019,6338000,"₹ 6,650/ sq ft",NaN,Under Construction,12
37536,1 rooms( pooja room ),NaN,"Lift Available,Car Parking,Power Backup,24 X 7...","1,218 sq ft",1,2,2 BHK Apartment,901 sq ft,East,"6,",...,New,4,Garden View,Freehold,01-12-2020,8100000,"₹ 6,650/ sq ft",NaN,Under Construction,12
37537,1 rooms( pooja room ),NaN,"Lift Available,Car Parking,Power Backup,24 X 7...","1,074 sq ft",1,2,2 BHK Apartment,796 sq ft,East,"6,",...,New,4,Garden View,Freehold,01-12-2018,7780000,"₹ 7,243/ sq ft",NaN,Under Construction,12
37538,"2 rooms( servant room, pooja room )",NaN,"Lift Available,Car Parking,Power Backup,24 X 7...","4,561 sq ft",2,4,4 BHK Apartment,3379 sq ft,West,"6,",...,New,4,Garden View,Freehold,01-06-2018,47800000,"₹ 10,480/ sq ft",NaN,Under Construction,12

In [146]:
# Dropping the Null values from col - price, bhk, neworold, locality
data.dropna(subset= ["bhk", "neworold", "locality", "price"], inplace = True)

In [147]:
data.isnull().sum().sort_values()

bhk                       0
neworold                  0
locality                  0
price                     0
pricepersquare            0
area                     20
status                 1460
bathroom               2871
amenitiesavailable     3093
floor                  5619
facing                 6619
ownership              9382
age                    9901
totalfloor            13424
balconies             15627
overlooking           20398
opensides             25933
additionalrooms       28217
carpetarea            28916
roadfaceing           30663
possesiondate         32802
dtype: int64

In [148]:
data.head(10)

,additionalrooms,age,amenitiesavailable,area,balconies,bathroom,bhk,carpetarea,facing,floor,...,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,roadfaceing,status,totalfloor
0,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,West,"3,",...,New,2,Road View,Co-Operative Society,NaN,27000000,"₹ 16,759/ sq ft",40 feet,Ready to move,6
1,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,7610050,"₹ 5,950/ sq ft",NaN,Ready to move,NaN
2,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",670 sq ft,NaN,1,1 BHK Apartment,NaN,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,4100000,"₹ 6,119/ sq ft",NaN,Ready to move,NaN
3,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,24 X 7...",956 sq ft,NaN,2,2 BHK Apartment,615 sq ft,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,5736000,"₹ 6,000/ sq ft",NaN,Ready to move,NaN
4,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,706 sq ft",1,3,3 BHK Apartment,1195 sq ft,West,"6,",...,New,2,Road View,Freehold,NaN,29002000,"₹ 17,000/ sq ft",60 feet,Ready to move,9
5,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,015 sq ft",2,2,2 BHK Apartment,NaN,NorthEast,"2,",...,New,2,"Garden View, Pool View, Road View",Freehold,NaN,4720765,"₹ 4,651/ sq ft",NaN,Ready to move,10
6,NaN,1 - 2 years,"Lift Available,Car Parking,Power Backup,24 X 7...","3,725 sq ft",NaN,5,4 BHK Apartment,NaN,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,30172500,"₹ 8,100/ sq ft",NaN,Ready to move,NaN
7,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",450 sq ft,NaN,1,1 BHK Apartment,NaN,NorthEast,1,...,New,NaN,NaN,Freehold,NaN,4000000,"₹ 8,889/ sq ft",NaN,Ready to move,NaN
8,"3 rooms( study room, servant room, pooja room )",1 - 2 years,"Lift Available,Car Parking,Power Backup,24 X 7...","1,650 sq ft",2,3,3 BHK Apartment,1150 sq ft,West,"4,",...,Resale,2,"Corner, Garden View, Road View",Freehold,NaN,24000000,"₹ 14,545/ sq ft",25 feet,"Ready to move,Unfurnished",6
9,NaN,0 - 1 year,"Lift Available,Power Backup,24 X 7 Security,Ch...",449 sq ft,1,1,1 BHK Apartment,NaN,NorthEast,"1,",...,New,2,"Road View, Garden View",Freehold,NaN,2783351,"₹ 6,199/ sq ft",NaN,Ready to move,15

In [149]:
data[data["additionalrooms"] == "additionalrooms"].sum().count()

np.int64(21)

In [150]:
rowtodrop = np.array(data[data["additionalrooms"] == "additionalrooms"].index)

In [151]:
data.drop(rowtodrop, inplace = True)

***Cleaning additional rooms col***

In [152]:
# Column- Additional Room
data["additionalrooms"].unique()

array([nan, '3 rooms( study room, servant room, pooja room )',
       '2 rooms( study room, pooja room )', '1 rooms( pooja room )',
       '1 rooms( servant room )', '1 rooms( study room )',
       '2 rooms( study room, servant room )',
       '2 rooms( servant room, pooja room )'], dtype=object)

In [153]:
def clean_additional_rooms(x):
  if pd.isnull(x):
    return np.nan
  return str(x).strip(" ")[0]

data["no. of additional rooms"] = data["additionalrooms"].apply(clean_additional_rooms)

In [154]:
# Comparing the both new col and original col
data.isnull().sum()

additionalrooms            28217
age                         9901
amenitiesavailable          3093
area                          20
balconies                  15627
bathroom                    2871
bhk                            0
carpetarea                 28916
facing                      6619
floor                       5619
locality                       0
neworold                       0
opensides                  25933
overlooking                20398
ownership                   9382
possesiondate              32802
price                          0
pricepersquare                 0
roadfaceing                30663
status                      1460
totalfloor                 13424
no. of additional rooms    28217
dtype: int64

In [155]:
data.head(10)

,additionalrooms,age,amenitiesavailable,area,balconies,bathroom,bhk,carpetarea,facing,floor,...,opensides,overlooking,ownership,possesiondate,price,pricepersquare,roadfaceing,status,totalfloor,no. of additional rooms
0,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,West,"3,",...,2,Road View,Co-Operative Society,NaN,27000000,"₹ 16,759/ sq ft",40 feet,Ready to move,6,NaN
1,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,NorthEast,1,...,NaN,NaN,Freehold,NaN,7610050,"₹ 5,950/ sq ft",NaN,Ready to move,NaN,NaN
2,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",670 sq ft,NaN,1,1 BHK Apartment,NaN,NorthEast,1,...,NaN,NaN,Freehold,NaN,4100000,"₹ 6,119/ sq ft",NaN,Ready to move,NaN,NaN
3,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,24 X 7...",956 sq ft,NaN,2,2 BHK Apartment,615 sq ft,NorthEast,1,...,NaN,NaN,Freehold,NaN,5736000,"₹ 6,000/ sq ft",NaN,Ready to move,NaN,NaN
4,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,706 sq ft",1,3,3 BHK Apartment,1195 sq ft,West,"6,",...,2,Road View,Freehold,NaN,29002000,"₹ 17,000/ sq ft",60 feet,Ready to move,9,NaN
5,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,015 sq ft",2,2,2 BHK Apartment,NaN,NorthEast,"2,",...,2,"Garden View, Pool View, Road View",Freehold,NaN,4720765,"₹ 4,651/ sq ft",NaN,Ready to move,10,NaN
6,NaN,1 - 2 years,"Lift Available,Car Parking,Power Backup,24 X 7...","3,725 sq ft",NaN,5,4 BHK Apartment,NaN,NorthEast,1,...,NaN,NaN,Freehold,NaN,30172500,"₹ 8,100/ sq ft",NaN,Ready to move,NaN,NaN
7,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",450 sq ft,NaN,1,1 BHK Apartment,NaN,NorthEast,1,...,NaN,NaN,Freehold,NaN,4000000,"₹ 8,889/ sq ft",NaN,Ready to move,NaN,NaN
8,"3 rooms( study room, servant room, pooja room )",1 - 2 years,"Lift Available,Car Parking,Power Backup,24 X 7...","1,650 sq ft",2,3,3 BHK Apartment,1150 sq ft,West,"4,",...,2,"Corner, Garden View, Road View",Freehold,NaN,24000000,"₹ 14,545/ sq ft",25 feet,"Ready to move,Unfurnished",6,3
9,NaN,0 - 1 year,"Lift Available,Power Backup,24 X 7 Security,Ch...",449 sq ft,1,1,1 BHK Apartment,NaN,NorthEast,"1,",...,2,"Road View, Garden View",Freehold,NaN,2783351,"₹ 6,199/ sq ft",NaN,Ready to move,15,NaN

In [156]:
# Extracting the study room as seprate col
def study_room(x):
  if pd.isnull(x):
    return np.nan
  elif "study" in x:
    return "Yes"
  else:
    return "No"

data["studyroom"] = data["additionalrooms"].apply(study_room)

In [157]:
# Extracting the pooja room as seprate col
def pooja_room(x):
  if pd.isnull(x):
    return np.nan
  elif "pooja" in x:
    return "Yes"
  else:
    return "No"

data["poojaroom"] = data["additionalrooms"].apply(pooja_room)

In [158]:
# Extracting the servant room as seprate col
def servant_room(x):
  if pd.isnull(x):
    return np.nan
  elif "servant" in x:
    return "Yes"
  else:
    return "No"

data["servantroom"] = data["additionalrooms"].apply(servant_room)

In [159]:
# comparing data
data[["additionalrooms","no. of additional rooms","studyroom","poojaroom","servantroom"]].isnull().sum()

additionalrooms            28217
no. of additional rooms    28217
studyroom                  28217
poojaroom                  28217
servantroom                28217
dtype: int64

In [160]:
data.head()

,additionalrooms,age,amenitiesavailable,area,balconies,bathroom,bhk,carpetarea,facing,floor,...,possesiondate,price,pricepersquare,roadfaceing,status,totalfloor,no. of additional rooms,studyroom,poojaroom,servantroom
0,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,West,"3,",...,NaN,27000000,"₹ 16,759/ sq ft",40 feet,Ready to move,6,NaN,NaN,NaN,NaN
1,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,NorthEast,1,...,NaN,7610050,"₹ 5,950/ sq ft",NaN,Ready to move,NaN,NaN,NaN,NaN,NaN
2,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",670 sq ft,NaN,1,1 BHK Apartment,NaN,NorthEast,1,...,NaN,4100000,"₹ 6,119/ sq ft",NaN,Ready to move,NaN,NaN,NaN,NaN,NaN
3,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,24 X 7...",956 sq ft,NaN,2,2 BHK Apartment,615 sq ft,NorthEast,1,...,NaN,5736000,"₹ 6,000/ sq ft",NaN,Ready to move,NaN,NaN,NaN,NaN,NaN
4,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,706 sq ft",1,3,3 BHK Apartment,1195 sq ft,West,"6,",...,NaN,29002000,"₹ 17,000/ sq ft",60 feet,Ready to move,9,NaN,NaN,NaN,NaN

In [161]:
# Dropping the additional room col
data.drop("additionalrooms", axis = 1, inplace = True)

In [162]:
data.head(2)

,age,amenitiesavailable,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,...,possesiondate,price,pricepersquare,roadfaceing,status,totalfloor,no. of additional rooms,studyroom,poojaroom,servantroom
0,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,West,"3,",Deccan Gymkhana,...,NaN,27000000,"₹ 16,759/ sq ft",40 feet,Ready to move,6,NaN,NaN,NaN,NaN
1,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,NorthEast,1,Kharadi,...,NaN,7610050,"₹ 5,950/ sq ft",NaN,Ready to move,NaN,NaN,NaN,NaN,NaN

***Cleaning age column***

In [163]:
data["age"]

0        2 - 3 years
1         0 - 1 year
2         0 - 1 year
3        2 - 3 years
4         0 - 1 year
            ...
37534     0 - 1 year
37535            NaN
37536            NaN
37537            NaN
37538            NaN
Name: age, Length: 37516, dtype: object

In [164]:
def clean_age(x):
    if pd.isnull(x):
        return np.nan

    x = str(x).lower().replace("years", "").replace("year", "").strip()

 # case = 2-3
    if "-" in x:
      a, b = x.split("-")
      return (int(a.strip()) + int(b.strip())) / 2

# case = 2
    else:
      return int(x)

In [165]:
data["age of house"] = data["age"].apply(clean_age)

In [166]:
data["age of house"].head()

0    2.5
1    0.5
2    0.5
3    2.5
4    0.5
Name: age of house, dtype: float64

In [167]:
data.drop("age", axis = 1, inplace= True)

In [168]:
data.sample()

,amenitiesavailable,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,...,price,pricepersquare,roadfaceing,status,totalfloor,no. of additional rooms,studyroom,poojaroom,servantroom,age of house
26506,"Lift Available,Car Parking,Power Backup,24 X 7...",874 sq ft,1,1,2 BHK Apartment,800 sq ft,East,"1,",Chakan,Resale,...,3100000,"₹ 3,546/ sq ft",NaN,"Ready to move,Unfurnished",11,NaN,NaN,NaN,NaN,NaN

***Cleaning "area" column***

In [169]:
def clean_area(x):
  if pd.isnull(x):
    return np.nan

  return int(str(x).split(" ")[0].replace(",",""))

data["total area"] = data["area"].apply(clean_area)

In [170]:
# Comparing original vs new col
data[["area", "total area"]]

              area  total area
0      1,611 sq ft      1611.0
1      1,279 sq ft      1279.0
2        670 sq ft       670.0
3        956 sq ft       956.0
4      1,706 sq ft      1706.0
...            ...         ...
37534  1,084 sq ft      1084.0
37535    953 sq ft       953.0
37536  1,218 sq ft      1218.0
37537  1,074 sq ft      1074.0
37538  4,561 sq ft      4561.0

[37516 rows x 2 columns]

In [171]:
# dropping area col
data.drop("area", axis = 1, inplace = True )

In [172]:
data.sample()

,amenitiesavailable,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,...,pricepersquare,roadfaceing,status,totalfloor,no. of additional rooms,studyroom,poojaroom,servantroom,age of house,total area
30731,"Lift Available,Car Parking,Power Backup,24 X 7...",1,1,1 BHK Apartment,NaN,NaN,NaN,Wagholi,Resale,NaN,...,"₹ 4,152/ sq ft",NaN,"Ready to move,Unfurnished",NaN,NaN,NaN,NaN,NaN,5.5,578.0

***Cleaning "bhk" column***

In [173]:
data["bhk"].unique()

array(['3 BHK Apartment ', '2 BHK Apartment ', '1 BHK Apartment ',
       '4 BHK Apartment ', ' Residential Plot ', '1 RK Apartment ',
       '3 BHK Villa ', '5 BHK Villa ', '4 BHK Independent House ',
       '4 BHK Villa ', '2 BHK Independent House ',
       '3 BHK Independent House ', '3 BHK Independent Floor ',
       '1 BHK Villa ', '4 BHK penthouse ', '3 BHK penthouse ',
       '5 BHK Apartment ', '1 BHK Independent Floor ', '2 BHK penthouse ',
       '2 BHK Villa ', '2 BHK Independent Floor ', '8 BHK Villa ',
       '6 BHK Apartment ', '5 BHK Independent House ',
       '1 BHK Independent House ', '1 BHK studio apartment ',
       '0 BHK Villa ', '5 BHK penthouse ', '1 RK Independent House ',
       '6 BHK Villa ', '6 BHK penthouse ', '5 BHK Independent Floor ',
       '4 BHK Independent Floor ', '3 BHK Other Residential ',
       '6 BHK Independent Floor ', '1 RK Independent Floor ',
       '7 BHK Independent House ', '4 BHK Other Residential ',
       '7 BHK Apartment '], dtype=object)

In [174]:
# Cleaning bhk col
def clean_bhk_totalrooms(x):
  if pd.isnull(x):
    return np.isnan

  x = str(x).strip().upper().split(" ")

  if x[0].isdigit():
    rooms = int(x[0])
    t = x[1]

    if t == "BHK":
      return rooms + 2
    elif t == "RK":
      return 2

  else:
    return np.nan

In [175]:
data["total rooms"] = data["bhk"].apply(clean_bhk_totalrooms)

In [176]:
data[["bhk","total rooms"]].head()

                bhk  total rooms
0  3 BHK Apartment           5.0
1  2 BHK Apartment           4.0
2  1 BHK Apartment           3.0
3  2 BHK Apartment           4.0
4  3 BHK Apartment           5.0

*Feature extraction from semi-structured text*

In [177]:
# Extracting Apartment Col from bhk

def check_apartment(x):
  x = str(x).lower()

  if "apartment" in x:
    return "Yes"
  else:
    return "No"

data["apartment"] = data["bhk"].apply(check_apartment)

In [178]:
# Extracting Residental Col from bhk

def check_residential(x):
  x = str(x).lower()

  if 'residential plot' in x:
    return 'Yes'
  else:
    return 'No'

data["residential"] = data["bhk"].apply(check_residential)

In [179]:
# Extracting Penthouse Col from bhk

def check_penthouse(x):
    x = str(x).lower()

    if "penthouse" in x:
        return "Yes"
    else:
        return "No"

data["penthouse"] = data["bhk"].apply(check_penthouse)

In [180]:
# Extracting Independent Col from bhk

def check_Independent(x):
    x = str(x).lower()
    return "Yes" if "independent" in x else "No"

data["independent"] = data["bhk"].apply(check_Independent)

In [181]:
# Extracting Villa Col from bhk

def check_villa(x):
    x = str(x).lower()
    if "villa" in x:
        return "Yes"
    else:
        return "No"

data["villa"] = data["bhk"].apply(check_villa)

In [182]:
data.isna().sum()

amenitiesavailable          3093
balconies                  15627
bathroom                    2871
bhk                            0
carpetarea                 28916
facing                      6619
floor                       5619
locality                       0
neworold                       0
opensides                  25933
overlooking                20398
ownership                   9382
possesiondate              32802
price                          0
pricepersquare                 0
roadfaceing                30663
status                      1460
totalfloor                 13424
no. of additional rooms    28217
studyroom                  28217
poojaroom                  28217
servantroom                28217
age of house                9901
total area                    20
total rooms                 1247
apartment                      0
residential                    0
penthouse                      0
independent                    0
villa                          0
dtype: int64

In [183]:
data.drop("bhk", axis = 1, inplace = True)

In [184]:
data.head(2)

,amenitiesavailable,balconies,bathroom,carpetarea,facing,floor,locality,neworold,opensides,overlooking,...,poojaroom,servantroom,age of house,total area,total rooms,apartment,residential,penthouse,independent,villa
0,"Lift Available,Car Parking,Power Backup,Indoor...",2,3,1209 sq ft,West,"3,",Deccan Gymkhana,New,2,Road View,...,NaN,NaN,2.5,1611.0,5.0,Yes,No,No,No,No
1,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NaN,NorthEast,1,Kharadi,New,NaN,NaN,...,NaN,NaN,0.5,1279.0,4.0,Yes,No,No,No,No

***Cleaning "carpet area" column***

In [185]:
data["carpetarea"].unique()

array(['1209 sq ft', nan, '615 sq ft', ..., '3630 sq ft', '1316 sq ft',
       '2804 sq ft'], dtype=object)

In [186]:
def clean_carpetarea(x):
  if pd.isnull(x):
    return np.nan

  return int(str(x).split(" ")[0])

data["carpet area"] = data["carpetarea"].apply(clean_carpetarea)

In [187]:
data[["carpetarea" , "carpet area"]].head(2)

   carpetarea  carpet area
0  1209 sq ft       1209.0
1         NaN          NaN

In [188]:
data[["carpetarea" , "carpet area"]].isnull().sum()

carpetarea     28916
carpet area    28916
dtype: int64

In [189]:
data.drop("carpetarea", axis = 1, inplace = True)

In [190]:
data.head(10)

,amenitiesavailable,balconies,bathroom,facing,floor,locality,neworold,opensides,overlooking,ownership,...,servantroom,age of house,total area,total rooms,apartment,residential,penthouse,independent,villa,carpet area
0,"Lift Available,Car Parking,Power Backup,Indoor...",2,3,West,"3,",Deccan Gymkhana,New,2,Road View,Co-Operative Society,...,NaN,2.5,1611.0,5.0,Yes,No,No,No,No,1209.0
1,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NorthEast,1,Kharadi,New,NaN,NaN,Freehold,...,NaN,0.5,1279.0,4.0,Yes,No,No,No,No,NaN
2,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,1,NorthEast,1,Sus,New,NaN,NaN,Freehold,...,NaN,0.5,670.0,3.0,Yes,No,No,No,No,NaN
3,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NorthEast,1,Bavdhan,New,NaN,NaN,Freehold,...,NaN,2.5,956.0,4.0,Yes,No,No,No,No,615.0
4,"Lift Available,Car Parking,Power Backup,24 X 7...",1,3,West,"6,",Deccan Gymkhana,New,2,Road View,Freehold,...,NaN,0.5,1706.0,5.0,Yes,No,No,No,No,1195.0
5,"Lift Available,Car Parking,Power Backup,24 X 7...",2,2,NorthEast,"2,",Mundhwa,New,2,"Garden View, Pool View, Road View",Freehold,...,NaN,0.5,1015.0,4.0,Yes,No,No,No,No,NaN
6,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,5,NorthEast,1,Viman Nagar,New,NaN,NaN,Freehold,...,NaN,1.5,3725.0,6.0,Yes,No,No,No,No,NaN
7,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,1,NorthEast,1,Baner,New,NaN,NaN,Freehold,...,NaN,0.5,450.0,3.0,Yes,No,No,No,No,NaN
8,"Lift Available,Car Parking,Power Backup,24 X 7...",2,3,West,"4,",Law collage Road,Resale,2,"Corner, Garden View, Road View",Freehold,...,Yes,1.5,1650.0,5.0,Yes,No,No,No,No,1150.0
9,"Lift Available,Power Backup,24 X 7 Security,Ch...",1,1,NorthEast,"1,",Mahalunge,New,2,"Road View, Garden View",Freehold,...,NaN,0.5,449.0,3.0,Yes,No,No,No,No,NaN

***Cleaning "floor" column***

In [191]:
data["floor"].unique()

array(['3, ', '1', '6, ', '2, ', '4, ', '1, ', '12, ', '14, ', nan, '7, ',
       '10, ', '8, ', '9, ', '11, ', '5, ', '16, ', '18, ', 'Gr ', '20, ',
       'Gr', '6', '7', '5', '2', '3', '4', '9', '10', '13, ', '21, ',
       '22, ', '24, ', '25, ', '14', '8', '12', '11', '15, ', '17, ',
       '19, ', '23, ', '18', '34, ', '13', '27, ', '17', '32, ', '15',
       '20', '31, ', '30, ', '16', '30', '19', '34', '26, '], dtype=object)

In [192]:
def clean_floor(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).strip().lower().replace(",","")

  if x.isdigit():
    return x
  else:
    return 0 # ground floor as 0th floor

In [193]:
data["floors"] = data["floor"].apply(clean_floor)

In [194]:
data["floors"].unique()

array(['3', '1', '6', '2', '4', '12', '14', nan, '7', '10', '8', '9',
       '11', '5', '16', '18', 0, '20', '13', '21', '22', '24', '25', '15',
       '17', '19', '23', '34', '27', '32', '31', '30', '26'], dtype=object)

In [195]:
data["floors"].sample(2)

14778     2
23345    10
Name: floors, dtype: object

In [196]:
data.drop("floor", axis = 1, inplace = True)

***Cleaning "new or old" column***

In [197]:
data["neworold"].unique()

array(['New', 'Resale'], dtype=object)

In [198]:
# Extracting New House from neworold col

def house_type(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()
  if x =="new":
    return "New"
  else:
    return "Old"

data["house type"] = data["neworold"].apply(house_type)

In [199]:
data["house type"]

0        New
1        New
2        New
3        New
4        New
        ...
37534    New
37535    New
37536    New
37537    New
37538    New
Name: house type, Length: 37516, dtype: object

In [200]:
data.drop("neworold", axis = 1, inplace = True)

In [201]:
data.head()

,amenitiesavailable,balconies,bathroom,facing,locality,opensides,overlooking,ownership,possesiondate,price,...,total area,total rooms,apartment,residential,penthouse,independent,villa,carpet area,floors,house type
0,"Lift Available,Car Parking,Power Backup,Indoor...",2,3,West,Deccan Gymkhana,2,Road View,Co-Operative Society,NaN,27000000,...,1611.0,5.0,Yes,No,No,No,No,1209.0,3,New
1,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NorthEast,Kharadi,NaN,NaN,Freehold,NaN,7610050,...,1279.0,4.0,Yes,No,No,No,No,NaN,1,New
2,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,1,NorthEast,Sus,NaN,NaN,Freehold,NaN,4100000,...,670.0,3.0,Yes,No,No,No,No,NaN,1,New
3,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NorthEast,Bavdhan,NaN,NaN,Freehold,NaN,5736000,...,956.0,4.0,Yes,No,No,No,No,615.0,1,New
4,"Lift Available,Car Parking,Power Backup,24 X 7...",1,3,West,Deccan Gymkhana,2,Road View,Freehold,NaN,29002000,...,1706.0,5.0,Yes,No,No,No,No,1195.0,6,New

***Cleaning "open side" column***

In [202]:
data["opensides"].unique()

array(['2', nan, '3', '1', '4'], dtype=object)

***Cleaning "overlooking" column***

In [203]:
data["overlooking"].head(10)

0                            Road View
1                                  NaN
2                                  NaN
3                                  NaN
4                            Road View
5    Garden View, Pool View, Road View
6                                  NaN
7                                  NaN
8       Corner, Garden View, Road View
9               Road View, Garden View
Name: overlooking, dtype: object

In [204]:
data["overlooking"].unique()

array(['Road View', nan, 'Garden View, Pool View, Road View',
       'Corner, Garden View, Road View', 'Road View, Garden View',
       'Corner, Garden View, Pool View, Road View', 'Corner',
       'Corner, Garden View', 'Road View, Corner', 'Garden View',
       'Pool View, Garden View', 'Corner, Pool View, Road View',
       'Pool View', 'Road View, Pool View', 'Pool View, Corner',
       'Corner, Garden View, Pool View'], dtype=object)

In [205]:
# Extracting the road view from ownership column

def check_road_view(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "road view" in x:
    return "Yes"
  else:
    return "No"

data["road view"] = data["overlooking"].apply(check_road_view)

In [206]:
data["road view"]

0        Yes
1        NaN
2        NaN
3        NaN
4        Yes
        ...
37534     No
37535     No
37536     No
37537     No
37538     No
Name: road view, Length: 37516, dtype: object

In [207]:
# Extracting the gaden view from ownership column

def check_garden_view(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "garden view" in x:
    return "Yes"
  else:
    return "No"

data["garden view"] = data["overlooking"].apply(check_garden_view)

In [208]:
data["garden view"]

0         No
1        NaN
2        NaN
3        NaN
4         No
        ...
37534    Yes
37535    Yes
37536    Yes
37537    Yes
37538    Yes
Name: garden view, Length: 37516, dtype: object

In [209]:
# Extracting the Pool View from ownership column

def check_phool_view(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "phool view" in x:
    return "Yes"
  else:
    return "No"

data["phool view"] = data["overlooking"].apply(check_phool_view)

In [210]:
# Extracting the Corner View from ownership column

def check_corner_view(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "corner view" in x:
    return "Yes"
  else:
    return "No"

data["corner view"] = data["overlooking"].apply(check_corner_view)

In [211]:
data["corner view"]

0         No
1        NaN
2        NaN
3        NaN
4         No
        ...
37534     No
37535     No
37536     No
37537     No
37538     No
Name: corner view, Length: 37516, dtype: object

In [212]:
data.drop("overlooking", axis = 1, inplace = True)

***Cleaning "ownership" column***

In [213]:
data["ownership"].unique()

array(['Co-Operative Society', 'Freehold', nan, 'Power of Attorney',
       'Leasehol'], dtype=object)

In [214]:
# Extracting the Co-Operative Society from ownership column

def check_society(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "co-operative society" in x:
    return "Yes"
  else:
    return "No"

data["co-operative society"] = data["ownership"].apply(check_society)

In [215]:
data["co-operative society"]

0        Yes
1         No
2         No
3         No
4         No
        ...
37534     No
37535     No
37536     No
37537     No
37538     No
Name: co-operative society, Length: 37516, dtype: object

In [216]:
# Extracting the Freehold

def check_freehold(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "freehold" in x:
    return "Yes"
  else:
    return "No"

data["freehold property"] = data["ownership"].apply(check_freehold)

In [217]:
data["freehold property"]

0         No
1        Yes
2        Yes
3        Yes
4        Yes
        ...
37534    Yes
37535    Yes
37536    Yes
37537    Yes
37538    Yes
Name: freehold property, Length: 37516, dtype: object

In [218]:
# Extracting the Power of Attorney from ownership column

def check_power_of_attorney(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "power of attorney" in x:
    return "Yes"
  else:
    return "No"

data["power of attorney"] = data["ownership"].apply(check_power_of_attorney)

In [219]:
data["power of attorney"]

0        No
1        No
2        No
3        No
4        No
         ..
37534    No
37535    No
37536    No
37537    No
37538    No
Name: power of attorney, Length: 37516, dtype: object

In [220]:
# Extracting the leasehold from ownership column

def check_leasehold(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()

  if "leasehol" in x:
    return "Yes"
  else:
    return "No"

data["leasehold"] = data["ownership"].apply(check_leasehold)

In [221]:
data["leasehold"]

0        No
1        No
2        No
3        No
4        No
         ..
37534    No
37535    No
37536    No
37537    No
37538    No
Name: leasehold, Length: 37516, dtype: object

In [222]:
data.sample()

,amenitiesavailable,balconies,bathroom,facing,locality,opensides,ownership,possesiondate,price,pricepersquare,...,floors,house type,road view,garden view,phool view,corner view,co-operative society,freehold property,power of attorney,leasehold
14813,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NaN,Viman Nagar,NaN,Freehold,NaN,6828000,"₹ 6,000/ sq ft",...,NaN,New,NaN,NaN,NaN,NaN,No,Yes,No,No

In [223]:
data.drop("ownership", axis = 1, inplace = True )

In [224]:
data.head()

,amenitiesavailable,balconies,bathroom,facing,locality,opensides,possesiondate,price,pricepersquare,roadfaceing,...,floors,house type,road view,garden view,phool view,corner view,co-operative society,freehold property,power of attorney,leasehold
0,"Lift Available,Car Parking,Power Backup,Indoor...",2,3,West,Deccan Gymkhana,2,NaN,27000000,"₹ 16,759/ sq ft",40 feet,...,3,New,Yes,No,No,No,Yes,No,No,No
1,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NorthEast,Kharadi,NaN,NaN,7610050,"₹ 5,950/ sq ft",NaN,...,1,New,NaN,NaN,NaN,NaN,No,Yes,No,No
2,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,1,NorthEast,Sus,NaN,NaN,4100000,"₹ 6,119/ sq ft",NaN,...,1,New,NaN,NaN,NaN,NaN,No,Yes,No,No
3,"Lift Available,Car Parking,Power Backup,24 X 7...",NaN,2,NorthEast,Bavdhan,NaN,NaN,5736000,"₹ 6,000/ sq ft",NaN,...,1,New,NaN,NaN,NaN,NaN,No,Yes,No,No
4,"Lift Available,Car Parking,Power Backup,24 X 7...",1,3,West,Deccan Gymkhana,2,NaN,29002000,"₹ 17,000/ sq ft",60 feet,...,6,New,Yes,No,No,No,No,Yes,No,No

***Cleaning "possesiondate" Column***

In [225]:
data["possesiondate"].unique()

array([nan, '01-11-2019', '01-03-2018', '01-12-2018', '01-12-2019',
       '01-07-2019', '01-12-2020', '01-12-2021', '01-09-2018',
       '01-06-2018', '01-04-2019', '01-04-2018', '01-08-2018',
       '01-09-2020', '01-12-2025', '01-10-2018', '01-03-2020',
       '01-03-2019', '01-07-2018', '01-06-2019', '01-11-2018',
       '01-08-2020', '01-12-2022', '01-09-2019', '01-05-2019',
       '01-05-2018', '01-02-2019', '01-01-2019', '01-01-2018',
       '01-02-2018', '01-02-2020', '01-09-2021', '01-08-2019',
       '01-10-2019', '01-06-2021', '01-10-2022', '01-06-2020',
       '01-03-2021', '01-11-2021', '01-09-2022', '01-07-2020',
       '01-11-2020', '01-12-2023', '01-10-2021', '01-07-2021',
       '01-01-2020', '01-02-2021', '01-05-2020', '01-08-2021',
       '01-02-2022', '01-03-2022', '01-05-2021'], dtype=object)

In [226]:
# Cleaning the possesion data column
# Extracting the year column

def possesion_year(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).strip().split("-")

  if x[-1].isdigit():
    return x[-1]

data["possesion year"] = data["possesiondate"].apply(possesion_year)

# Extracting the Month Column

def possesion_month(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).strip().split("-")

  if x[-1].isdigit():
    return x[1]

data["possesion month"] = data["possesiondate"].apply(possesion_month)

In [227]:
data[["possesiondate", "possesion year", "possesion month"]]

      possesiondate possesion year possesion month
0               NaN            NaN             NaN
1               NaN            NaN             NaN
2               NaN            NaN             NaN
3               NaN            NaN             NaN
4               NaN            NaN             NaN
...             ...            ...             ...
37534           NaN            NaN             NaN
37535    01-12-2019           2019              12
37536    01-12-2020           2020              12
37537    01-12-2018           2018              12
37538    01-06-2018           2018              06

[37516 rows x 3 columns]

***Cleaning "road faceing " Column***

In [228]:
data["roadfaceing"].unique()

array(['40 feet', nan, '60 feet', '25 feet', '50 feet', '20 feet',
       '100 feet', '30 feet', '15 feet', '80 feet', '10 feet', '120 feet',
       '45 feet', '36 feet', '32 feet', '90 feet', '150 feet', '200 feet',
       '7 feet', '180 feet', '35 feet', '65 feet', '219 feet', '196 feet',
       '209 feet', '70 feet', '18 feet', '98 feet', '250 feet', '42 feet',
       '38 feet', '400 feet', '6 feet', '131 feet', '34 feet', '48 feet',
       '55 feet', '19 feet', '164 feet', '328 feet', '8 feet', '26 feet',
       '29 feet', '110 feet', '16 feet', '350 feet', '9 feet', '22 feet',
       '656 feet', '12 feet', '39 feet', '59 feet', '300 feet', '82 feet',
       '72 feet', '271 feet', '295 feet', '23 feet', '68 feet', '49 feet',
       '14 feet', '160 feet', '27 feet', '13 feet', '66 feet', '262 feet',
       '17 feet', '1 feet', '984 feet', '52 feet', '54 feet', '1000 feet',
       '2 feet', '500 feet', '780 feet', '85 feet', '5 feet', '24 feet',
       '170 feet', '11 feet', '6561 feet', '492 feet', '190 feet',
       '114 feet'], dtype=object)

In [229]:
# Cleaning Roadfaceing Column

def clean_road_feet(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).strip().split(" ")
  return int(x[0])

data["road feet"] = data["roadfaceing"].apply(clean_road_feet)

In [230]:
data["road feet"]

0        40.0
1         NaN
2         NaN
3         NaN
4        60.0
         ...
37534     NaN
37535     NaN
37536     NaN
37537     NaN
37538     NaN
Name: road feet, Length: 37516, dtype: float64

In [231]:
data.drop("roadfaceing" , axis = 1 , inplace = True)

***Cleaning the "status" column***

In [232]:
data["status"].unique()

array(['Ready to move', 'Ready to move,Unfurnished', 'Under Construction',
       'Ready to move,Furnished', 'Unfurnished',
       'Ready to move,Semi-Furnished',
       'Under Construction,Semi-Furnished', nan,
       'Under Construction,Unfurnished', 'Semi-Furnished', 'Furnished',
       'Under Construction,Furnished'], dtype=object)

In [233]:
# Extracting the "Read to move" from status col

def check_read_to_move(x):
  if pd.isnull(x):
    return np.nan

  x = str(x).lower()
  if "read to move" in x:
    return "Yes"
  else:
    return "No"

data["ready to move"] = data["status"].apply(check_read_to_move)

# Extracting the "Unfurnished" from status col

def check_unfurnished(x):
  x = str(x).lower()
  if pd.isnull(x):
    return np.nan
  elif "unfurnished" in x:
    return "Yes"
  else:
    return "No"

data["unfurnished"] = data["status"].apply(check_unfurnished)

# Extracting the "Under Construction' from status col

def check_under_construction(x):
  x = str(x).lower()
  if pd.isnull(x):
    return np.nan
  elif "under construction" in x:
    return "Yes"
  else:
    return "No"

data["under construction"] = data["status"].apply(check_under_construction)


# Extracting the "Semi furnished' from status col

def check_semi_furnished(x):
  x = str(x).lower()
  if pd.isnull(x):
    return np.nan
  elif "Semi-Furnished" in x:
    return "Yes"
  else:
    return "No"

data["semi furnished"] = data["status"].apply(check_semi_furnished)

# Extracting the "furnished" from status col

def check_furnished(x):
  x = str(x).lower()
  if pd.isnull(x):
    return np
  elif "furnished" in x:
    return "Yes"
  else:
    return "No"

data["furnished"] = data["status"].apply(check_furnished)

In [234]:
data[["ready to move", "unfurnished", "under construction","semi furnished","furnished"]]

      ready to move unfurnished under construction semi furnished furnished
0                No          No                 No             No        No
1                No          No                 No             No        No
2                No          No                 No             No        No
3                No          No                 No             No        No
4                No          No                 No             No        No
...             ...         ...                ...            ...       ...
37534            No          No                 No             No        No
37535            No          No                Yes             No        No
37536            No          No                Yes             No        No
37537            No          No                Yes             No        No
37538            No          No                Yes             No        No

[37516 rows x 5 columns]

In [235]:
data.drop("status" , axis = 1 , inplace = True)

***Cleaning "amenities available" column***

In [236]:
data["amenitiesavailable"].unique()

array(['Lift Available,Car Parking,Power Backup,Indoor Games,Intercom,Landscaped Gardens,Gas connection',
       'Lift Available,Car Parking,Power Backup,24 X 7 Security,Vaastu Compliant,Club House,Gymnasium,Swimming Pool,Jogging Track,Rain Water Harvesting',
       "Lift Available,Car Parking,Power Backup,24 X 7 Security,Children's play area,Vaastu Compliant,Club House,Gymnasium,Swimming Pool,Indoor Games,Jogging Track,Maintenance Staff,Intercom,Rain Water Harvesting,Staff Quarter,Landscaped Gardens",
       ...,
       'Car Parking,24 X 7 Security,Vaastu Compliant,Shopping Mall,School,Hospital,ATM,Refrigerator',
       "Car Parking,Power Backup,Children's play area,Vaastu Compliant,Gymnasium,Sports Facility,Jogging Track,Maintenance Staff,Rain Water Harvesting,Multipurpose Room,Landscaped Gardens,Shopping Mall,School,Hospital,ATM,Wardrobe",
       "Lift Available,Car Parking,Power Backup,24 X 7 Security,Children's play area,Vaastu Compliant,Club House,Gymnasium,Swimming Pool,Sports Facility,Indoor Games,Jogging Track,Maintenance Staff,Intercom,Cafeteria,Rain Water Harvesting,Staff Quarter,Multipurpose Room,Landscaped Gardens,Shopping Mall,School,Hospital,ATM,Refrigerator,Gas connection"],
      dtype=object)

In [237]:
d = np.array(data["amenitiesavailable"].dropna())

In [238]:
ls = max(d, key = len)
ls = ls.split(",")
ls

['Lift Available',
 'Car Parking',
 'Power Backup',
 '24 X 7 Security',
 "Children's play area",
 'Vaastu Compliant',
 'Club House',
 'Gymnasium',
 'Swimming Pool',
 'Sports Facility',
 'Indoor Games',
 'Jogging Track',
 'Maintenance Staff',
 'Intercom',
 'Golf Course',
 'Cafeteria',
 'Rain Water Harvesting',
 'Staff Quarter',
 'Multipurpose Room',
 'Landscaped Gardens',
 'Shopping Mall',
 'School',
 'Hospital',
 'ATM',
 'AC',
 'Wardrobe',
 'TV',
 'Refrigerator',
 'Sofa',
 'Washing Machine',
 'Wifi',
 'Microwave',
 'Dining Table',
 'Gas connection',
 'BED']

In [239]:
for i in ls:
  def check_amenities(x):
    x = str(x)

    if i in x:
      return "Yes"
    else:
      return "No"

  data[i] = data['amenitiesavailable'].apply(check_amenities)

In [240]:
data.columns

Index(['amenitiesavailable', 'balconies', 'bathroom', 'facing', 'locality',
       'opensides', 'possesiondate', 'price', 'pricepersquare', 'totalfloor',
       'no. of additional rooms', 'studyroom', 'poojaroom', 'servantroom',
       'age of house', 'total area', 'total rooms', 'apartment', 'residential',
       'penthouse', 'independent', 'villa', 'carpet area', 'floors',
       'house type', 'road view', 'garden view', 'phool view', 'corner view',
       'co-operative society', 'freehold property', 'power of attorney',
       'leasehold', 'possesion year', 'possesion month', 'road feet',
       'ready to move', 'unfurnished', 'under construction', 'semi furnished',
       'furnished', 'Lift Available', 'Car Parking', 'Power Backup',
       '24 X 7 Security', 'Children's play area', 'Vaastu Compliant',
       'Club House', 'Gymnasium', 'Swimming Pool', 'Sports Facility',
       'Indoor Games', 'Jogging Track', 'Maintenance Staff', 'Intercom',
       'Golf Course', 'Cafeteria', 'Rain Water Harvesting', 'Staff Quarter',
       'Multipurpose Room', 'Landscaped Gardens', 'Shopping Mall', 'School',
       'Hospital', 'ATM', 'AC', 'Wardrobe', 'TV', 'Refrigerator', 'Sofa',
       'Washing Machine', 'Wifi', 'Microwave', 'Dining Table',
       'Gas connection', 'BED'],
      dtype='object')

In [241]:
data.drop("amenitiesavailable" , axis = 1 , inplace = True)

In [242]:
data.shape

(37516, 75)

In [243]:
data.isnull().sum()

balconies         15627
bathroom           2871
facing             6619
locality              0
opensides         25933
                  ...
Wifi                  0
Microwave             0
Dining Table          0
Gas connection        0
BED                   0
Length: 75, dtype: int64

In [244]:
data["AC"].value_counts()

AC
No     35342
Yes     2174
Name: count, dtype: int64

***Dropping the Duplicates***

In [245]:
data.duplicated().sum()

np.int64(7853)

In [246]:
data.drop_duplicates(inplace = True)
data.duplicated().sum()

np.int64(0)

In [247]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29663 entries, 0 to 37455
Data columns (total 75 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   balconies                17717 non-null  object
 1   bathroom                 27810 non-null  object
 2   facing                   24735 non-null  object
 3   locality                 29663 non-null  object
 4   opensides                8434 non-null   object
 5   possesiondate            3447 non-null   object
 6   price                    29663 non-null  object
 7   pricepersquare           29663 non-null  object
 8   totalfloor               19400 non-null  object
 9   no. of additional rooms  7312 non-null   object
 10  studyroom                7312 non-null   object
 11  poojaroom                7312 non-null   object
 12  servantroom              7312 non-null   object
 13  age of house             22454 non-null  float64
 14  total area               29650 non-null  float64
 15  total rooms              29019 non-null  float64
 16  apartment                29663 non-null  object
 17  residential              29663 non-null  object
 18  penthouse                29663 non-null  object
 19  independent              29663 non-null  object
 20  villa                    29663 non-null  object
 21  carpet area              6546 non-null   float64
 22  floors                   25686 non-null  object
 23  house type               29663 non-null  object
 24  road view                13553 non-null  object
 25  garden view              13553 non-null  object
 26  phool view               13553 non-null  object
 27  corner view              13553 non-null  object
 28  co-operative society     22786 non-null  object
 29  freehold property        22786 non-null  object
 30  power of attorney        22786 non-null  object
 31  leasehold                22786 non-null  object
 32  possesion year           3447 non-null   object
 33  possesion month          3447 non-null   object
 34  road feet                5129 non-null   float64
 35  ready to move            28832 non-null  object
 36  unfurnished              29663 non-null  object
 37  under construction       29663 non-null  object
 38  semi furnished           29663 non-null  object
 39  furnished                29663 non-null  object
 40  Lift Available           29663 non-null  object
 41  Car Parking              29663 non-null  object
 42  Power Backup             29663 non-null  object
 43  24 X 7 Security          29663 non-null  object
 44  Children's play area     29663 non-null  object
 45  Vaastu Compliant         29663 non-null  object
 46  Club House               29663 non-null  object
 47  Gymnasium                29663 non-null  object
 48  Swimming Pool            29663 non-null  object
 49  Sports Facility          29663 non-null  object
 50  Indoor Games             29663 non-null  object
 51  Jogging Track            29663 non-null  object
 52  Maintenance Staff        29663 non-null  object
 53  Intercom                 29663 non-null  object
 54  Golf Course              29663 non-null  object
 55  Cafeteria                29663 non-null  object
 56  Rain Water Harvesting    29663 non-null  object
 57  Staff Quarter            29663 non-null  object
 58  Multipurpose Room        29663 non-null  object
 59  Landscaped Gardens       29663 non-null  object
 60  Shopping Mall            29663 non-null  object
 61  School                   29663 non-null  object
 62  Hospital                 29663 non-null  object
 63  ATM                      29663 non-null  object
 64  AC                       29663 non-null  object
 65  Wardrobe                 29663 non-null  object
 66  TV                       29663 non-null  object
 67  Refrigerator             29663 non-null  object
 68  Sofa                     29663 non-null  object
 69  Washing Machine          29663 non-null  object
 70  Wifi                     29663 non-null  object
 71  Microwave                29663 non-null  object
 72  Dining Table             29663 non-null  object
 73  Gas connection           29663 non-null  object
 74  BED                      29663 non-null  object
dtypes: float64(5), object(70)
memory usage: 17.2+ MB

***Converting the numeric col to numeric***

In [248]:
data.drop("pricepersquare" ,axis = 1, inplace = True)

***Conversting data to numeric***

In [249]:
data =(data.apply(pd.to_numeric, errors = "ignore"))

/tmp/ipython-input-3067257550.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data =(data.apply(pd.to_numeric, errors = "ignore"))

In [250]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29663 entries, 0 to 37455
Data columns (total 74 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   balconies                17717 non-null  float64
 1   bathroom                 27810 non-null  float64
 2   facing                   24735 non-null  object
 3   locality                 29663 non-null  object
 4   opensides                8434 non-null   float64
 5   possesiondate            3447 non-null   object
 6   price                    29663 non-null  int64
 7   totalfloor               19400 non-null  float64
 8   no. of additional rooms  7312 non-null   float64
 9   studyroom                7312 non-null   object
 10  poojaroom                7312 non-null   object
 11  servantroom              7312 non-null   object
 12  age of house             22454 non-null  float64
 13  total area               29650 non-null  float64
 14  total rooms              29019 non-null  float64
 15  apartment                29663 non-null  object
 16  residential              29663 non-null  object
 17  penthouse                29663 non-null  object
 18  independent              29663 non-null  object
 19  villa                    29663 non-null  object
 20  carpet area              6546 non-null   float64
 21  floors                   25686 non-null  float64
 22  house type               29663 non-null  object
 23  road view                13553 non-null  object
 24  garden view              13553 non-null  object
 25  phool view               13553 non-null  object
 26  corner view              13553 non-null  object
 27  co-operative society     22786 non-null  object
 28  freehold property        22786 non-null  object
 29  power of attorney        22786 non-null  object
 30  leasehold                22786 non-null  object
 31  possesion year           3447 non-null   float64
 32  possesion month          3447 non-null   float64
 33  road feet                5129 non-null   float64
 34  ready to move            28832 non-null  object
 35  unfurnished              29663 non-null  object
 36  under construction       29663 non-null  object
 37  semi furnished           29663 non-null  object
 38  furnished                29663 non-null  object
 39  Lift Available           29663 non-null  object
 40  Car Parking              29663 non-null  object
 41  Power Backup             29663 non-null  object
 42  24 X 7 Security          29663 non-null  object
 43  Children's play area     29663 non-null  object
 44  Vaastu Compliant         29663 non-null  object
 45  Club House               29663 non-null  object
 46  Gymnasium                29663 non-null  object
 47  Swimming Pool            29663 non-null  object
 48  Sports Facility          29663 non-null  object
 49  Indoor Games             29663 non-null  object
 50  Jogging Track            29663 non-null  object
 51  Maintenance Staff        29663 non-null  object
 52  Intercom                 29663 non-null  object
 53  Golf Course              29663 non-null  object
 54  Cafeteria                29663 non-null  object
 55  Rain Water Harvesting    29663 non-null  object
 56  Staff Quarter            29663 non-null  object
 57  Multipurpose Room        29663 non-null  object
 58  Landscaped Gardens       29663 non-null  object
 59  Shopping Mall            29663 non-null  object
 60  School                   29663 non-null  object
 61  Hospital                 29663 non-null  object
 62  ATM                      29663 non-null  object
 63  AC                       29663 non-null  object
 64  Wardrobe                 29663 non-null  object
 65  TV                       29663 non-null  object
 66  Refrigerator             29663 non-null  object
 67  Sofa                     29663 non-null  object
 68  Washing Machine          29663 non-null  object
 69  Wifi                     29663 non-null  object
 70  Microwave                29663 non-null  object
 71  Dining Table             29663 non-null  object
 72  Gas connection           29663 non-null  object
 73  BED                      29663 non-null  object
dtypes: float64(13), int64(1), object(60)
memory usage: 17.0+ MB

In [251]:
data.duplicated().sum()

np.int64(12)

***Saving the Clean dataset***

In [252]:
data.drop_duplicates(inplace= True)

In [254]:
data.to_csv("cleaned_pune_property_ds.csv", index = False)